# Generated by Django 4.2.1 on 2023-05-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardSelection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
