# Generated by Django 4.2.1 on 2023-06-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardSelection', '0002_topic_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('board_name', models.CharField(max_length=40)),
                ('subject_name', models.CharField(max_length=40)),
                ('class_name', models.CharField(max_length=25)),
                ('chapter_name', models.CharField(max_length=40)),
                ('pdf_link', models.CharField(max_length=255)),
            ],
        ),
    ]
